### ISSUE TITLE
Add Travis (or some other CI)

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-to-cabal#14]
@Profpatsch noticed a couple of problems while (presumably) trying to build `dhall-to-cabal` - firstly hitting some missing files. A CI server would have caught this. I haven't really set one of these up before, but if anyone has experience, this would be a great help.

**Comment by joneshf** [comment]
Do you have a particular CI you'd like to use (Travis, Circle, etc)? What all do you want to check? What is the current build process that you go through? I'm more than willing to help for this. More Dhall projects is a good thing!

If you are interested in Travis and looking for a straight forward setup, I find https://github.com/haskell-hvr/multi-ghc-travis really nice for that. The YAML file it makes is maybe a bit complex since it does so much and uses cabal directly (so maintaining it afterward takes a bit of understanding).

If you want something a little less complex there are templates for Travis with Stack: https://docs.haskellstack.org/en/stable/travis_ci/#travis-ci.

Mostly just depends on what you want to do. Since you're the main person contributing here, it might be better if the CI process was similar to your own development process. That way, even if _how_ a particular CI works is unfamiliar at the moment, you at least have some idea of _what_ CI is supposed to be doing.

**Comment by ocharles** [comment]
@joneshf Thanks for your questions!

> Do you have a particular CI you'd like to use (Travis, Circle, etc)?

The best one? :smile: I haven't used any of them, so I have no preference.

> What all do you want to check?

That the build succeeds and that tests pass.

> What is the current build process that you go through?

`cabal build` and `cabal test`.

> Mostly just depends on what you want to do. Since you're the main person contributing here, it might be better if the CI process was similar to your own development process. That way, even if how a particular CI works is unfamiliar at the moment, you at least have some idea of what CI is supposed to be doing.

All very reasonable points. I think my development approach is very idiomatic Haskell - it's just pure Cabal and Hackage. Sure, there is dhall-to-cabal.dhall that generates dhall-to-cabal.cabal, but I'm not too concerned about having CI know about that for now.

**Comment by Profpatsch** [comment]
Maybe @grahamc’s @ofborg can be used?

**Comment by Profpatsch** [comment]
Maybe @grahamc’s [ofborg](https://github.com/NixOS/ofborg/) can be used?

**Comment by ocharles** [comment]
No idea, but if someone contributes a PR that sets it up and doesn't require me to run any server software then I'm OK with that.

**Comment by grahamc** [comment]
I think for now ofborg wouldn't do what you're looking for, and something like Travis would be an easier/more suitable tool. It is pretty easy to set it up with Nix:

```
language: nix
sudo: false

script: nix-build ./release.nix
```

**Comment by ocharles** [comment]
Unfortunately it doesn't seem as easy as @grahamc suggests. I've added that, but the build just seems to timeout: https://travis-ci.org/ocharles/dhall-to-cabal/builds/336764097

**Comment by Profpatsch** [comment]
Seeing all these packages being downloaded makes my heart (and hydra’s resources) bleed …

Anyway, since `Dhall.Core` is a rather large module that compiles for nearly 30s on my 4-core machine, I suspect travis just doesn’t assign enough resources for it to be fast enough for the timeout reaper.
A dirty hack would be to put a `echo "alive"; sleep 10` script in the background~

**Comment by joneshf** [comment]
If it's really timing out–but still making progress–there is `travis_wait`: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received. It does essentially what @Profpatsch suggested. It will extend the timeout to 20 minutes by default (you can adjust the time).

So if you wanted a 45 minute timeout, you would say something like:

```YAML
script: travis_wait 45 nix-build ./shell.nix
```

Sorry, I don't have enough experience with `nix` to be more useful here.

**Comment by ocharles** [comment]
Even a 20 minute timeout still doesn't work. I might try hvr's scripts, but I can't them working with GHC 8.2 :disappointed:

**Comment by ocharles** [comment]
@Gabriel439 - now that `dhall-haskell` is built on your Hydra, could this also be added? I'm happy to help pay for the running costs.

**Comment by Gabriel439** [comment]
Yeah, I was already going to propose adding `dhall-to-cabal`, but I just forgot!  It's very cheap to add a new job and the entire instance only costs about $10 / month, so don't worry about the costs.  One of the reasons I set it up was because I was running into the same Travis timeouts for my projects and the Hydra CI is much smarter about not rebuilding unchanged dependencies

I can deploy add a `dhall-to-cabal` CI job later tonight because it's managed from my personal laptop

Later on I would like to add an OS X build slave so that we can serve pre-built OS X binaries, but then the cost starts to grow (~ $50 / month for OS X hosting)

**Comment by Gabriel439** [comment]
@ocharles: Actually, you have to do this and you already have permission to do so.  Go to the Settings page of `dhall-to-cabal` and at the very bottom you will have the option to move the repository to any organization where you have permission to create repositories (which includes the `dhall-lang` organization), so you can migrate the repository yourself

**Comment by ocharles** [comment]
Ok, repo moved! Do I need to do anything else?

**Comment by Gabriel439** [comment]
That's all you need to do.  I should be able to add CI for `dhall-to-cabal` tonight because now the `dhall-bot` has sufficient permission for your repository

**Comment by ocharles** [comment]
Perfect, thank you! Please go ahead and close this once you're done. I no longer have access to settings, so I can't enable mandatory status checks for PRs.

**Comment by Gabriel439** [comment]
@ocharles: I restored you as an admin of this repository

**Comment by Gabriel439** [comment]
Alright, I set up Hydra CI for `dhall-to-cabal`: https://hydra.dhall-lang.org/project/dhall-to-cabal

However, it is currently failing with an evaluation error because it expects a `release.nix` file in the top-level directory containing a set of derivations to build.  Once you add that file it will begin successfully building pull requests

**Comment by ocharles** [comment]
All done!
